spring:
  profiles:
    active: embedded
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: embedded
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
---
spring:
  config:
    activate:
      on-profile: debug
  datasource:
    url: jdbc:postgresql://localhost:5432/servicebuilder_test
    username: bconnors
    password: Sh!re7942
